SELECT
EXTRACT(YEAR FROM SALES_DATE)   AS YEAR,
EXTRACT(MONTH FROM SALES_DATE)  AS MONTH,
A.GENDER,
COUNT(DISTINCT B.USER_ID)       AS USERS
FROM 
USER_INFO A,
ONLINE_SALE B
WHERE A.GENDER IS NOT NULL AND A.USER_ID = B.USER_ID 
GROUP BY EXTRACT(YEAR FROM SALES_DATE),EXTRACT(MONTH FROM SALES_DATE),A.GENDER
ORDER BY 1,2,3